name: Kapture
options:
  bundleIdPrefix: com.kapture
  deploymentTarget:
    iOS: "17.0"
  developmentLanguage: en
  createIntermediateGroups: true
  
targets:
  Kapture:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: Kapture
        excludes:
          - "**/*Tests.swift"
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.kapture.app
      PRODUCT_NAME: Kapture
      SWIFT_VERSION: "5.9"
      IPHONEOS_DEPLOYMENT_TARGET: "17.0"
      INFOPLIST_FILE: Kapture/Info.plist
      INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
      INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
      INFOPLIST_KEY_UILaunchScreen_Generation: YES
      INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
      INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
      CODE_SIGN_STYLE: Automatic
      DEVELOPMENT_TEAM: ""
    info:
      path: Kapture/Info.plist
      properties:
        CFBundleDisplayName: Kapture
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleName: $(PRODUCT_NAME)
        CFBundlePackageType: $(PRODUCT_BUNDLE_PACKAGE_TYPE)
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        LSRequiresIPhoneOS: YES
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: YES
        UIApplicationSupportsIndirectInputEvents: YES
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        CFBundleURLTypes:
          - CFBundleURLSchemes:
              - kapture
            CFBundleURLName: com.kapture.oauth
          
  KaptureWidget:
    type: app-extension
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: KaptureWidget
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.kapture.widget
      PRODUCT_NAME: KaptureWidget
      SWIFT_VERSION: "5.9"
      IPHONEOS_DEPLOYMENT_TARGET: "17.0"
      INFOPLIST_FILE: KaptureWidget/Info.plist
      CODE_SIGN_STYLE: Automatic
      DEVELOPMENT_TEAM: ""
    info:
      path: KaptureWidget/Info.plist
      properties:
        CFBundleDisplayName: KaptureWidget
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleName: $(PRODUCT_NAME)
        CFBundlePackageType: $(PRODUCT_BUNDLE_PACKAGE_TYPE)
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        NSExtension:
          NSExtensionPointIdentifier: com.apple.widgetkit-extension
          
  KaptureTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: KaptureTests
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.kapture.tests
      PRODUCT_NAME: KaptureTests
      SWIFT_VERSION: "5.9"
      IPHONEOS_DEPLOYMENT_TARGET: "17.0"
      TEST_TARGET_NAME: Kapture
    dependencies:
      - target: Kapture

